title: Boyuan Gong
description: Deep Learning Research assiatant in TAMU. Focusing on adversarial examples and network stability.

email: boyuangong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog I share my thoughts in deep learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gongboyuan
github_username:  boyuangong

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]
